"""
=============================================================
 HomeLab Hub
-------------------------------------------------------------
 File:
     env.py

 Description:
     Configures the Alembic migration environment for the
     HomeLab Hub database.

     The migration environment uses the same SQLite database
     URL and SQLAlchemy model metadata as the application.

 Author:
     H A (GitHub: i-xul)

 License:
     MIT License
=============================================================
"""

from __future__ import annotations

from logging.config import fileConfig

from alembic import context
from sqlalchemy import engine_from_config
from sqlalchemy import pool

from app.database.database import DATABASE_URL
from app.models import Base


# ---------------------------------------------------------
# Alembic configuration
# ---------------------------------------------------------

config = context.config

# Use the same database location as the HomeLab Hub backend.
config.set_main_option(
    "sqlalchemy.url",
    DATABASE_URL,
)

if config.config_file_name is not None:
    fileConfig(config.config_file_name)


# ---------------------------------------------------------
# SQLAlchemy model metadata
# ---------------------------------------------------------

# Alembic compares this metadata against the current database
# schema when an autogenerated migration is requested.
target_metadata = Base.metadata


# ---------------------------------------------------------
# Offline migration mode
# ---------------------------------------------------------


def run_migrations_offline() -> None:
    """
    Run migrations without creating a live database connection.

    Offline mode produces SQL statements using only the
    configured database URL.
    """

    database_url = config.get_main_option("sqlalchemy.url")

    context.configure(
        url=database_url,
        target_metadata=target_metadata,
        literal_binds=True,
        dialect_opts={
            "paramstyle": "named",
        },
        compare_type=True,
    )

    with context.begin_transaction():
        context.run_migrations()


# ---------------------------------------------------------
# Online migration mode
# ---------------------------------------------------------


def run_migrations_online() -> None:
    """
    Run migrations using a live database connection.

    SQLite batch rendering is enabled so that future schema
    alterations can be handled safely when SQLite does not
    support a direct ALTER TABLE operation.
    """

    connectable = engine_from_config(
        config.get_section(
            config.config_ini_section,
            {},
        ),
        prefix="sqlalchemy.",
        poolclass=pool.NullPool,
    )

    with connectable.connect() as connection:
        context.configure(
            connection=connection,
            target_metadata=target_metadata,
            compare_type=True,
            render_as_batch=True,
        )

        with context.begin_transaction():
            context.run_migrations()


# ---------------------------------------------------------
# Migration mode selection
# ---------------------------------------------------------

if context.is_offline_mode():
    run_migrations_offline()
else:
    run_migrations_online()
